blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/5FtvrR3ryG
    about: Discord Server for Support. Join our community
  - name: Email Me
    url: mailto:aditya.funs.11@gmail.com
    about: Email Support
